{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "oxidized.pvcName" . }}
  namespace: {{ include "oxidized.namespace" . }}
  labels:
    {{- include "oxidized.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  {{- with include "oxidized.storageClass" . }}
  {{- . | nindent 2 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
