{{- if and .Values.runtimeSecret.create (not .Values.runtimeSecret.existingSecret) }}
{{- $secretKeys := .Values.runtimeSecret.secretKeys -}}
{{- $data := .Values.runtimeSecret.data -}}
{{- $deviceUsernameKey := $secretKeys.deviceUsernameKey | default $secretKeys.defaultUsernameKey -}}
{{- $devicePasswordKey := $secretKeys.devicePasswordKey | default $secretKeys.defaultPasswordKey -}}
{{- $readonlyDeviceUsernameKey := $secretKeys.readonlyDeviceUsernameKey | default $secretKeys.readonlyUsernameKey -}}
{{- $readonlyDevicePasswordKey := $secretKeys.readonlyDevicePasswordKey | default $secretKeys.readonlyPasswordKey -}}
{{- $deviceUsername := $data.deviceUsername | default $data.defaultUsername -}}
{{- $devicePassword := $data.devicePassword | default $data.defaultPassword -}}
{{- $readonlyDeviceUsername := $data.readonlyDeviceUsername | default $data.readonlyUsername -}}
{{- $readonlyDevicePassword := $data.readonlyDevicePassword | default $data.readonlyPassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oxidized.runtimeSecretName" . }}
  namespace: {{ include "oxidized.namespace" . }}
  labels:
    {{- include "oxidized.labels" . | nindent 4 }}
    app.kubernetes.io/component: credentials
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ $deviceUsernameKey }}: {{ $deviceUsername | default "" | quote }}
  {{ $devicePasswordKey }}: {{ $devicePassword | default "" | quote }}
  {{ .Values.runtimeSecret.secretKeys.netboxApiTokenKey }}: {{ .Values.runtimeSecret.data.netboxApiToken | quote }}
  {{ $readonlyDeviceUsernameKey }}: {{ $readonlyDeviceUsername | default "" | quote }}
  {{ $readonlyDevicePasswordKey }}: {{ $readonlyDevicePassword | default "" | quote }}
{{- end }}
