{{- if and .Values.sshSecret.create (not .Values.sshSecret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oxidized.sshSecretName" . }}
  namespace: {{ include "oxidized.namespace" . }}
  labels:
    {{- include "oxidized.labels" . | nindent 4 }}
    app.kubernetes.io/component: credentials
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- if .Values.sshSecret.data.id_rsa }}
  id_rsa: |
{{ .Values.sshSecret.data.id_rsa | trimSuffix "\n" | indent 4 }}
  {{- else }}
  id_rsa: ""
  {{- end }}
  {{- if .Values.sshSecret.data.id_rsa_pub }}
  id_rsa.pub: |
{{ .Values.sshSecret.data.id_rsa_pub | trimSuffix "\n" | indent 4 }}
  {{- else }}
  id_rsa.pub: ""
  {{- end }}
  {{- if .Values.sshSecret.data.known_hosts }}
  known_hosts: |
{{ .Values.sshSecret.data.known_hosts | trimSuffix "\n" | indent 4 }}
  {{- else }}
  known_hosts: ""
  {{- end }}
{{- end }}
