apiVersion: v1
kind: Service
metadata:
  name: {{ include "oxidized.fullname" . }}
  namespace: {{ include "oxidized.namespace" . }}
  labels:
    {{- include "oxidized.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- if or .Values.commonAnnotations .Values.service.annotations }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "oxidized.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
